# Generated by Django 4.2.16 on 2026-04-10 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_location_licensure_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_address', models.CharField(blank=True, max_length=300)),
                ('site_city', models.CharField(blank=True, max_length=100)),
                ('site_type', models.CharField(choices=[('ems_field', 'EMS Field'), ('er', 'Emergency Department'), ('icu', 'ICU'), ('fire', 'Fire Department'), ('other', 'Other')], max_length=50)),
                ('rotation_date', models.DateField()),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('hours_completed', models.DecimalField(decimal_places=1, max_digits=4)),
                ('patient_contacts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rotation_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentSiteEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('site_organization', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('site_learning_opportunities', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('site_equipment_available', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('site_patient_volume', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('site_staff_welcoming', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('site_would_return', models.BooleanField(blank=True, null=True)),
                ('preceptor_knowledge', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('preceptor_teaching_style', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('preceptor_feedback_quality', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('preceptor_professionalism', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('preceptor_overall', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('best_part_of_rotation', models.TextField(blank=True)),
                ('what_could_be_improved', models.TextField(blank=True)),
                ('would_you_recommend', models.BooleanField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('rotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_eval', to='evaluations.clinicalrotation')),
            ],
            options={
                'verbose_name': 'Student site evaluation',
            },
        ),
        migrations.CreateModel(
            name='PreceptorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preceptor_name', models.CharField(max_length=200)),
                ('preceptor_email', models.EmailField(max_length=254)),
                ('preceptor_title', models.CharField(blank=True, max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expires', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting preceptor'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('link_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('preceptor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('appearance_professional', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('punctuality', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('communication_patients', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('communication_team', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('attitude_motivation', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('patient_assessment', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('clinical_skills_performance', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('critical_thinking', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('medical_knowledge', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('documentation', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('overall_performance', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('recommended_to_pass', models.BooleanField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('rotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preceptor_eval', to='evaluations.clinicalrotation')),
            ],
            options={
                'verbose_name': 'Preceptor evaluation',
            },
        ),
    ]
