# Generated by Django 4.2.16 on 2026-04-11 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_location_licensure_dates'),
        ('students', '0003_sig_textfields_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychomotorSkillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('evaluation_date', models.DateField()),
                ('passed', models.BooleanField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('evaluator_name', models.CharField(max_length=200)),
                ('evaluator_qualifications', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('site_name', models.CharField(max_length=200)),
                ('contact_type', models.CharField(choices=[('field', 'Field Experience'), ('clinical', 'Clinical Training'), ('simulated', 'Simulated Patient Encounter'), ('ed', 'Emergency Department'), ('other', 'Other')], max_length=50)),
                ('supervisor_name', models.CharField(max_length=200)),
                ('supervisor_license_level', models.CharField(blank=True, max_length=50)),
                ('patient_age_group', models.CharField(blank=True, choices=[('adult', 'Adult'), ('pediatric', 'Pediatric'), ('geriatric', 'Geriatric'), ('obstetric', 'Obstetric')], max_length=20)),
                ('chief_complaint', models.CharField(blank=True, max_length=200)),
                ('iv_start_attempted', models.BooleanField(default=False)),
                ('iv_start_successful', models.BooleanField(default=False)),
                ('airway_placement_attempted', models.BooleanField(default=False)),
                ('airway_placement_successful', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_contacts_rec', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contact_date'],
            },
        ),
        migrations.CreateModel(
            name='EntranceRequirementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('document_on_file', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_requirements', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requirement_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_agency_name', models.CharField(default='Panhandle EMS Education', max_length=200)),
                ('course_location', models.CharField(max_length=300)),
                ('instructor_names', models.TextField(help_text='Names of all instructors for this course')),
                ('students_enrolled', models.PositiveIntegerField(default=0)),
                ('students_withdrew', models.PositiveIntegerField(default=0)),
                ('students_completed', models.PositiveIntegerField(default=0)),
                ('total_didactic_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_clinical_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_field_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('report_submitted_to_department', models.BooleanField(default=False)),
                ('report_submitted_date', models.DateField(blank=True, null=True)),
                ('submission_deadline', models.DateField(blank=True, help_text='30 days after course completion', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_report', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CognitiveExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam_date', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseCompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('withdrew', models.BooleanField(default=False)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('didactic_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('clinical_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('field_internship_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('verified_by_name', models.CharField(blank=True, max_length=200)),
                ('verified_by_title', models.CharField(blank=True, max_length=200)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_issued_date', models.DateField(blank=True, null=True)),
                ('nremt_eligibility_sent', models.BooleanField(default=False)),
                ('nremt_eligibility_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
