# Generated by Django 4.2.16 on 2026-04-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_psychomotorskillrecord_patientcontactrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletionrecord',
            name='nremt_cognitive_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursecompletionrecord',
            name='nremt_cognitive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecompletionrecord',
            name='nremt_cognitive_result',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending'), ('not_taken', 'Not taken')], default='not_taken', max_length=10),
        ),
        migrations.AddField(
            model_name='coursecompletionrecord',
            name='nremt_psychomotor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecompletionrecord',
            name='nremt_psychomotor_result',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending'), ('not_taken', 'Not taken')], default='not_taken', max_length=10),
        ),
    ]
