# Generated by Django 4.2.16 on 2026-04-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_nremt_outcome_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instructor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_certifications',
            field=models.TextField(blank=True, help_text='Additional certifications, comma-separated'),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_employer_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_license_level',
            field=models.CharField(blank=True, choices=[('EMR', 'EMR Instructor'), ('EMT', 'EMT Instructor'), ('AEMT', 'AEMT Instructor'), ('Paramedic', 'Paramedic Instructor')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_primary',
            field=models.BooleanField(default=False, help_text='Primary instructor for a course'),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor_years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('staff', 'Office Staff'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
