# Generated by Django 4.2.16 on 2026-07-31 19:25
# Split into add → backfill → enforce-unique so existing rows don't collide
# on a single evaluated default (see Django docs on adding unique fields).

import uuid

from django.db import migrations, models


def backfill_calendar_tokens(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        student.calendar_token = uuid.uuid4()
        student.save(update_fields=['calendar_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='calendar_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True,
                                    help_text='Secret token used in the ICS feed URL for phone calendar subscriptions'),
        ),
        migrations.RunPython(backfill_calendar_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='calendar_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True,
                                    help_text='Secret token used in the ICS feed URL for phone calendar subscriptions'),
        ),
    ]
