# Generated by Django 4.2.16 on 2026-08-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_book_price_courseenrollment_book_included_and_more'),
        ('students', '0009_student_calendar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Leave blank to show to all students. Select a course to show only to that course enrollment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='courses.course'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional. Announcement automatically hides after this date/time.', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to publish immediately. Set a future date/time to schedule.', null=True),
        ),
    ]
