# Generated by Django 4.2.16 on 2026-08-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_announcement_course_announcement_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletionrecord',
            name='records_flagged_for_review',
            field=models.BooleanField(default=False, help_text='Flag when retention period is ending and records should be reviewed before deletion'),
        ),
        migrations.AddField(
            model_name='coursecompletionrecord',
            name='retain_until',
            field=models.DateField(blank=True, help_text='Records must be retained minimum 5 years per 172 NAC Chapter 13. Auto-set on completion.', null=True),
        ),
    ]
