# Generated by Django 5.1.8 on 2026-08-11 21:18

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional profile photo. Helps instructors learn student names.', null=True, upload_to=students.models.profile_photo_path),
        ),
    ]
