# Generated by Django 5.1.8 on 2026-08-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_latepaymentfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
