# Generated by Django 5.1.8 on 2026-08-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_webhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_director_name', models.CharField(default='Dr. Sheila Webb-Bowles', max_length=200)),
                ('medical_director_phone', models.CharField(default='308.630.3711', max_length=30)),
                ('medical_director_title', models.CharField(default='Medical Director, PEMSE', max_length=200)),
                ('agency_name', models.CharField(default='Panhandle EMS Education, LLC', max_length=200)),
                ('agency_address', models.CharField(default='709 Rosedale Dr., Scottsbluff, NE 69361', max_length=300)),
                ('agency_phone', models.CharField(default='308.631.2424', max_length=30)),
                ('agency_email', models.CharField(default='emseducation19@gmail.com', max_length=200)),
                ('agency_director', models.CharField(default='Robin Darnall', max_length=200)),
                ('agency_director_title', models.CharField(default='Program Director', max_length=200)),
                ('asst_director', models.CharField(blank=True, max_length=200)),
                ('asst_director_title', models.CharField(blank=True, max_length=200)),
                ('ne_approval_number', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
