# Generated by Django 4.2.16 on 2026-07-25 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_book_price_courseenrollment_book_included_and_more'),
        ('staff', '0002_staffinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinvitation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='courses.course'),
        ),
    ]
