# Generated by Django 5.1.8 on 2026-08-12 00:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_book_price_courseenrollment_book_included_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_score', models.DecimalField(decimal_places=2, default=100, help_text='Starts at 100. Staff deduct points per handbook policy.', max_digits=5)),
                ('fisdap_attempt_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fisdap_attempt_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fisdap_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'student__last_name'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('excused_absence', 'Excused absence (-10 points)'), ('unexcused_absence', 'Unexcused absence (-25 points)'), ('sleeping', 'Sleeping in class (-25 points)'), ('disruptive', 'Argumentative/Disruptive (-25 points)'), ('cheating', 'Cheating (-50 points)'), ('other', 'Other (custom amount)')], max_length=30)),
                ('points', models.PositiveIntegerField(help_text='Points deducted')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_deductions', to='grades.gradebook')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participation_deductions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SectionExamGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_final_exam', models.BooleanField(default=False, help_text='Mark True for the Final Written Exam')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('was_reset', models.BooleanField(default=False)),
                ('reset_count', models.PositiveIntegerField(default=0, help_text='Max 2 resets per handbook')),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_grades_entered', to=settings.AUTH_USER_MODEL)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_exam_grades', to='grades.gradebook')),
            ],
            options={
                'ordering': ['is_final_exam', 'exam_number'],
            },
        ),
        migrations.CreateModel(
            name='SkillsGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('date_evaluated', models.DateField(blank=True, null=True)),
                ('evaluator_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_grades_entered', to=settings.AUTH_USER_MODEL)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_grades', to='grades.gradebook')),
            ],
            options={
                'ordering': ['skill_name', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_grades_entered', to=settings.AUTH_USER_MODEL)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_grades', to='grades.gradebook')),
            ],
            options={
                'ordering': ['assignment_name'],
            },
        ),
        migrations.CreateModel(
            name='QuizGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
                ('quiz_number', models.PositiveIntegerField(help_text='e.g. 1, 2, 3 matching the course schedule')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('was_reset', models.BooleanField(default=False)),
                ('missed_excused', models.BooleanField(default=False, help_text='Max score 75% per handbook')),
                ('missed_unexcused', models.BooleanField(default=False, help_text='Score = 0 per handbook')),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_grades_entered', to=settings.AUTH_USER_MODEL)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_grades', to='grades.gradebook')),
            ],
            options={
                'ordering': ['quiz_number', 'attempt_number'],
                'unique_together': {('gradebook', 'quiz_number')},
            },
        ),
    ]
