# Generated by Django 5.1.8 on 2026-08-12 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_gradechangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradebook',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gradebooks_finalized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='finalized_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gradebook',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
