# Generated by Django 5.1.8 on 2026-08-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_gradebook_finalized_at_gradebook_finalized_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradebook',
            name='fisdap_attempt_1',
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='fisdap_attempt_2',
        ),
        migrations.RemoveField(
            model_name='gradebook',
            name='fisdap_passed',
        ),
    ]
