# Generated by Django 4.2.16 on 2026-04-28 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_course_location_licensure_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture / Didactic'), ('lab', 'Skills Lab'), ('simulation', 'Simulation'), ('clinical', 'Clinical'), ('field', 'Field Experience'), ('testing', 'Exam / Testing'), ('other', 'Other')], max_length=30)),
                ('session_topic', models.CharField(blank=True, max_length=300)),
                ('session_start', models.TimeField(blank=True, null=True)),
                ('session_end', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
                'unique_together': {('course', 'session_date', 'session_type')},
            },
        ),
        migrations.CreateModel(
            name='RemediationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_identified', models.TextField()),
                ('plan_details', models.TextField()),
                ('target_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('extended', 'Extended')], default='active', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('instructor_acknowledged', models.BooleanField(default=False)),
                ('instructor_signature', models.TextField(blank=True, help_text='Base64 canvas signature')),
                ('retain_until', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans_created', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('session_observed', models.CharField(max_length=200)),
                ('preparation', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('content_knowledge', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('delivery', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('student_engagement', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('time_management', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('professionalism', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('strengths', models.TextField(blank=True)),
                ('opportunities', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('overall_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('instructor_acknowledged', models.BooleanField(default=False)),
                ('instructor_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('instructor_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_observations', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('observed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_notes_written', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_notes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('meeting_type', models.CharField(choices=[('semi_annual', 'Semi-Annual Review'), ('remediation', 'Remediation Meeting'), ('other', 'Other')], max_length=20)),
                ('topics_discussed', models.TextField()),
                ('action_items', models.TextField(blank=True)),
                ('next_meeting_date', models.DateField(blank=True, null=True)),
                ('instructor_acknowledged', models.BooleanField(default=False)),
                ('instructor_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('instructor_signature', models.TextField(blank=True, help_text='Base64 canvas signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_conducted', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructionalHourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture / Didactic'), ('lab', 'Skills Lab'), ('simulation', 'Simulation'), ('clinical', 'Clinical Supervision'), ('field', 'Field Experience Supervision'), ('testing', 'Exam / Testing'), ('remediation', 'Remediation'), ('meeting', 'Instructor Meeting'), ('preparation', 'Course Preparation'), ('other', 'Other')], max_length=30)),
                ('topic_covered', models.CharField(max_length=300)),
                ('students_present', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_logs', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_logs', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hours_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late (arrived after start)'), ('excused', 'Excused absence'), ('makeup', 'Make-up session')], default='present', max_length=20)),
                ('arrival_time', models.TimeField(blank=True, help_text='Actual arrival time if late', null=True)),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='instructor.attendancerecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='InstructorCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary Instructor'), ('assistant', 'Assistant Instructor'), ('skills', 'Skills Evaluator'), ('clinical', 'Clinical Supervisor'), ('guest', 'Guest / Subject Matter Expert')], max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'role'],
                'unique_together': {('instructor', 'course', 'role')},
            },
        ),
    ]
