# Generated by Django 5.1.8 on 2026-08-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_attendancerecord_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorcourseassignment',
            name='can_enter_grades',
            field=models.BooleanField(default=False, help_text='Grants instructor ability to enter quiz and skills grades only.'),
        ),
    ]
