# Generated by Django 4.2.16 on 2026-04-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=200)),
                ('hint', models.CharField(blank=True, max_length=300)),
                ('required', models.BooleanField(default=True)),
                ('icon_color', models.CharField(default='#854f0b', max_length=7)),
                ('icon_bg', models.CharField(default='#faeeda', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.student_document_path)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected — re-upload required')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes (rejection reason, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='documents.documenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type__order'],
                'unique_together': {('student', 'doc_type')},
            },
        ),
    ]
