# Generated by Django 4.2.16 on 2026-08-06 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_book_price_courseenrollment_book_included_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(upload_to=documents.models.instructor_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank to show to all students, regardless of course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_documents', to='courses.course')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
