# Generated by Django 4.2.16 on 2026-08-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_instructordocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Expiration date for CPR cards and licenses', null=True),
        ),
    ]
