# Generated by Django 4.2.16 on 2026-04-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='licensure',
            field=models.CharField(blank=True, choices=[('EMR', 'Emergency Medical Responder (EMR)'), ('EMT', 'Emergency Medical Technician (EMT)'), ('AEMT', 'Advanced EMT (AEMT)'), ('PARA', 'Paramedic'), ('CE', 'Continuing Education'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='location_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='location_name',
            field=models.CharField(blank=True, help_text='e.g. Scottsbluff Fire Station 1', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='location_state',
            field=models.CharField(blank=True, default='NE', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_close_date',
            field=models.DateField(blank=True, help_text='Course disappears from registration page after this date', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_notes',
            field=models.TextField(blank=True, help_text='e.g. Mondays and Wednesdays 6-10pm'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
