# Generated by Django 4.2.16 on 2026-07-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_location_licensure_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra cost added to tuition if the student chooses the physical textbook. Leave at 0 to hide the textbook option.', max_digits=8),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='book_included',
            field=models.BooleanField(default=False, help_text='Student chose to include the physical textbook'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base tuition, without textbook', max_digits=8),
        ),
    ]
