# Generated by Django 5.1.8 on 2026-08-12 02:38

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_book_price_courseenrollment_book_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.course_syllabus_path),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
